### PR TITLE
Initial refactor from Ember-CLI

### PR DESCRIPTION
**Pull request by athomann**
This PR is far from done.  Refactored Ember-CLI to work with Mern.  Commands: [mern new AppName, mern generate component ComponentName]

### CODE REVIEW

**Comment by mayankchd** [comment]
Thanks @athomann, will take a look!

**Comment by stephan281094** [comment]
Isn't this a bit of an overkill? I also notice that `mern-cli` no longer uses git clone to get the [mern-starter](/hashnode/mern-starter) repository. How does this script get the latest version now?

Aside from that there are a lot of references to the Ember CLI. Even Ember email addresses.

I do like the new commands as it makes more sense and provides more flexibility.

**Comment by athomann** [comment]
@stephan281094 I admit that this pull request is far from done.  Angular did something similar by forking the ember-cli with angular-cli.  Looks like the wrote a script to remove any reference to ember-cli.
 https://github.com/angular/angular-cli

This branch currently doesn't pull the latest version.

**Comment by Antonin-Deniau** [comment]
Some change have been made:
- The script now pull the latest mern-starter version on github
- Scaffolding commands are avaiables for containers, components, controller and model
- I removed all occurence i've found of ember-cli
- I removed all dead code i've found

**Comment by somus** [comment]
Great work! Thanks for the PR, @athomann and @Antonin-Deniau. But, we have refactored the CLI to enable the cli to clone different variants of MERN from different repositories. You can check the code in v2 branch.

**Pull request closed without merging**
